[package]
name = "TUIAudioPlayer"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive"] }
inquire = "0.9.1"
lofty = "0.22.4"
ratatui = "0.29.0"
rodio = "0.21.1"
